---
jobs:
- name: push-s3-broker
  plan:
  - get: s3-broker-app
    trigger: true
  - task: build
    file: s3-broker-app/ci/build.yml
    params:
      AWS_ACCESS_KEY: {{test-aws-access-key-id}}
      AWS_SECRET_KEY: {{test-aws-secret-access-key}}
  - put: deploy-s3-broker-app
    params:
      manifest: s3-broker-build/manifest.yml
      current_app_name: s3-broker
      environment_variables:
        SECURITY_USER_NAME: {{staging-auth-name}}
        SECURITY_USER_PASSWORD: {{staging-auth-pass}}
        AWS_ACCESS_KEY: {{aws-access-key-id}}
        AWS_SECRET_KEY: {{aws-secret-access-key}}

    on_failure:
      put: slack
      params:
        text: |
          :x: FAILED to deploy s3-broker on production
          <https://ci.cloud.gov/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: Successfully deployed s3-broker on production
          <https://ci.cloud.gov/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}

  - task: update-broker
    file: s3-broker-app/ci/update-broker.yml
    params:
      <<: *staging-cf-creds
      # Note: name must match application name in manifest
      BROKER_NAME: s3-service-broker
      AUTH_USER: {{staging-auth-name}}
      AUTH_PASS: {{staging-auth-pass}}
      PLAN_NAME: s3

- name: acceptance-tests-staging
  plan:
  - get: s3-broker-app
    passed: [push-s3-broker]
    trigger: true
  - task: smoke-tests-s3
    file: s3-broker-app/ci/run-smoke-tests.yml
    params:
      <<: *staging-cf-creds
      SERVICE_PLAN: basic

resources:
- name: s3-broker-app
  type: git
  source:
    uri: {{s3-broker-url}}
    branch: {{s3-broker-branch}}

- name: deploy-s3-broker-app
  type: cf
  source:
    api: {{staging-cf-api-url}}
    username: {{staging-cf-deploy-username}}
    password: {{staging-cf-deploy-password}}
    organization: {{staging-cf-organization}}
    space: {{staging-cf-space}}
    skip_cert_check: false

- name: slack
  type: slack-notification
  source:
    url: {{slack-webhook-url}}

staging-cf-creds: &staging-cf-creds
  CF_API_URL: {{staging-cf-api-url}}
  CF_DEPLOY_USERNAME: {{staging-cf-deploy-username}}
  CF_DEPLOY_PASSWORD: {{staging-cf-deploy-password}}
  CF_ORGANIZATION: {{staging-cf-organization}}
  CF_SPACE: {{staging-cf-space}}
